sudo: required

services:
    - docker

before_install:
    - docker pull fedora:latest

script:
    - docker run --rm -v $(pwd):/code fedora /bin/bash -c "dnf install meson libsolv-devel libmodulemd-devel && meson builddir && ninja -C builddir && G_TEST_SRCDIR=$(pwd)/tests ./builddir/tests"
