language: c

sudo: required

services:
    - docker

before_install:
    - docker pull fedora:latest

script:
    - docker run --rm -v $(pwd):/code fedora /bin/bash -c "dnf install -y meson libsolv-devel libmodulemd-devel && cd /code && meson builddir && ninja -C builddir test"
